[Web] Create chat module
boostcamp-2020/Project02-A-RealTime-Translation-Messenger pull request #254
Opened 2020-12-08 09:44 UTC by kas136

### 🍞 Issue Number 

close: #252 
<br/>

### 🥞 작업 내역

> 구현 내용 및 작업 했던 내역

- [ ] chat 모듈 생성

<br/>

### 🍞 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트
  <br/>

### 🥞 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?
  <br/>

2020-12-08 14:42 UTC, pje1740 commented on client/src/modules/chat.ts
> +      state.chatLogs.data = action.payload;
채팅은 받아오는 거 자체는 하나의 채팅에 대한 객체 하나고, 이걸 배열로 data에서 쌓는 거면 payloadAction<ChatLogsType>이 되는 게 맞으려나요!
그리고 data에 갈아끼우는 느낌이 아니라, 기존의 배열에 하나의 객체가 append되는 걸로 로직을 작성해야될 거 같아요!
![image](https://user-images.githubusercontent.com/38778829/101498066-0328d600-39af-11eb-9f6f-0667119567d9.png)
이런식으로??

2020-12-08 14:43 UTC, pje1740 reviewed
코멘트 남겨뒀습니다!

2020-12-09 01:17 UTC, kas136 commented on client/src/modules/chat.ts
> +      state.chatLogs.data = action.payload;
아 그렇네요

2020-12-09 01:33 UTC, moaikang requested changes

2020-12-09 01:33 UTC, moaikang commented on client/src/hooks/useChat.tsx
> +import { ChatLogsType } from '../@types/types';
라이브러리와 import 분리 해주시면 좋을거 같아요!

2020-12-09 01:44 UTC, pje1740 approved these changes
깔끔한 거 같습니다!!

2020-12-09 01:45 UTC, moaikang approved these changes

2020-12-09 01:45 UTC, moaikang commented
👍👍

2020-12-09 02:04 UTC, pje1740 approved these changes
새로운 거 알아갑니다!!!

2020-12-09 03:11 UTC, merged